Allow multiline input for comments / render comments as markdown
MaibornWolff/SecObserve pull request #1406
Opened 2024-04-17 18:33 UTC by dervoeti

This removes the 255 character limit from comments, adds support for multiple lines in comments and renders them as markdown in the "show" view an observation log entry. In the observation log list, comments are shortened to 255 characters (plus three dots, if they are longer than 255 characters).

2024-04-18 16:55 UTC, StefanFl requested changes
It's a great enhancement

2024-04-18 16:55 UTC, StefanFl commented on backend/application/core/models.py
> +    comment = TextField()
All other fields have a limitation of the length, I would like to see that here as well. Shouldn't 2048 or 4096 characters be enough for a comment?

2024-04-18 16:55 UTC, StefanFl commented on backend/application/core/api/serializers_observation.py
> +    comment = CharField(required=True)
see remark about the size limitiation in the model

2024-04-18 16:55 UTC, StefanFl commented on backend/application/core/api/serializers_observation.py
> +    comment = CharField(required=True)
see remark about the size limitiation in the model

2024-04-18 16:55 UTC, StefanFl commented on backend/application/core/api/serializers_observation.py
> +    comment = CharField(required=True)
see remark about the size limitiation in the model

2024-04-18 16:55 UTC, StefanFl commented on frontend/src/core/observation_logs/ObservationLogEmbeddedList.tsx
> +                    <TextField source="comment_shortened" sortable={false} />
```suggestion
                    <TextField source="comment_shortened" sortable={false} label="Comment" />
```

2024-04-18 16:55 UTC, StefanFl commented on frontend/src/core/observation_logs/ObservationLogEmbeddedList.tsx
> +    listContext.data.forEach((element: any) => {
We should have this in the `ObservationLogApprovalList` as well.

2024-04-18 16:55 UTC, StefanFl commented on frontend/src/core/observations/ObservationAssessment.tsx
> +                        <TextInputWide multiline={true} source="comment" validate={validate_required} />
```suggestion
                        <TextInputWide multiline={true} source="comment" validate={validate_required} minRows={3} />
```

and see remark about the size limitiation in the model

2024-04-18 16:55 UTC, StefanFl commented on frontend/src/core/observations/ObservationBulkAssessment.tsx
> +                        <TextInputWide source="comment" validate={validate_required} />
```suggestion
                        <TextInputWide source="comment" validate={validate_required} minRows={3} />
```

and see remark about the size limitiation in the model

2024-04-18 16:55 UTC, StefanFl commented on frontend/src/core/observations/ObservationRemoveAssessment.tsx
> +                        <TextInputWide source="comment" validate={validate_required} />
```suggestion
                        <TextInputWide source="comment" validate={validate_required} minRows={3} />
```

and see remark about the size limitiation in the model

2024-04-18 19:53 UTC, dervoeti commented
Thanks! Addressed all of your comments.

2024-04-19 05:19 UTC, StefanFl requested changes
A few more remarks

2024-04-19 05:19 UTC, StefanFl commented on backend/application/core/migrations/0038_alter_observation_log_comment.py
> +            field=models.TextField(),
The migration needs to be regenerated.

2024-04-19 05:19 UTC, StefanFl commented on docker/frontend/dev.Dockerfile
> +FROM node:20.11.1-alpine3.19@sha256:c0a3badbd8a0a760de903e00cedbca94588e609299820557e72cba2a53dbaa2c as build
This file shouldn't be here. It shouldn't be needed anyway. `docker compose build` / `docker compose up` starts the frontend in development mode with hot reloading.

2024-04-19 05:19 UTC, StefanFl commented on frontend/.env.example
> +API_BASE_URL=http://localhost:8000/api
This file shouldn't be here.

2024-04-19 05:19 UTC, StefanFl commented on frontend/runtime-env.js
> +window.__RUNTIME_CONFIG__ = {"API_BASE_URL":"http://localhost:8000/api","OIDC_ENABLE":"true","OIDC_AUTHORITY":"http://localhost:8080/realms/secobserve","OIDC_CLIENT_ID":"secobserve","OIDC_REDIRECT_UR
This file shouldn't be here.

2024-04-19 07:43 UTC, dervoeti commented
Right, accidentally committed some of my local dev files, I'll streamline my setup later today so I won't need those files anymore. Regenerated the migration as well.

2024-04-19 09:41 UTC, StefanFl requested changes
Sorry, 2 minor issues slipped through before

2024-04-19 09:41 UTC, StefanFl commented on frontend/src/core/observations/ObservationBulkAssessment.tsx
> +                        <TextInputWide source="comment" validate={validate_required_4096} minRows={3} />
```suggestion
                        <TextInputWide source="comment" validate={validate_required_4096} multiline={true} minRows={3} />
```

2024-04-19 09:41 UTC, StefanFl commented on frontend/src/core/observations/ObservationRemoveAssessment.tsx
> +                        <TextInputWide source="comment" validate={validate_required_4096} minRows={3} />
```suggestion
                        <TextInputWide source="comment" validate={validate_required_4096} multiline={true} minRows={3} />
```

2024-04-19 13:47 UTC, dervoeti commented
Fixed :slightly_smiling_face:

2024-04-19 14:13 UTC, StefanFl approved these changes

2024-04-19 14:13 UTC, merged